### ISSUE TITLE
How to use shapebuffer

### ISSUE THREAD

**Issue by JosiahParry** [Esri/arcgis-pbf#10]
The [README](https://github.com/Esri/arcgis-pbf/blob/main/proto/FeatureCollection/README.md) does a great job describing how geometry is recorded. However, it is possible that geometry can be an `esriShapeBuffer` which is _not_ documented. 

How would the esriShapeBuffer be handled? I suspect this would be present if a request modified the `Feature Encoding`
<img width="465" alt="image" src="https://github.com/Esri/arcgis-pbf/assets/13534508/b518f615-f7ed-4841-b5a0-82295ab525de">

https://github.com/Esri/arcgis-pbf/blob/bfd92d7a5943ef1ef2ed91384bc5cb6b9ee2a4fd/proto/FeatureCollection/FeatureCollection.proto#L127

**Comment by mmgeorge** [comment]
@JosiahParry, we don't actually use shape buffers on the web, that's more for desktop clients that already support shapebuffers and would prefer to consume geometries that way due to existing code paths. I don't think there's going to be any real benefit to using shape buffers over esriDefault unless you already are using some library that only supports shape buffers, at which point you would just request with esriCompressedShapeBuffer and drop it in.

**Comment by JosiahParry** [comment]
Sounds good then!
