### ISSUE TITLE
Are polygon rings closed? 

### ISSUE THREAD

**Issue by JosiahParry** [Esri/arcgis-pbf#12]
The example of interpreting a polygon in the readme has the folllowing example: 

```
geometry: {
  geometryType: 3 (esriGeometryTypePolygon)
  coords: [256, 256, 2, 0, 0, 2, -2, 0, 0, -2, 56, 56, 2, 0, 0, 2, -2, 0, 0, -2]
  lengths: [5, 5]
}
```

Can you confirm that the pbf representation for polygons _does not_ close the rings? If this is the case, can it please be documented? 

~~However, the 5th set of coordinates is  `0, -2` which would not be a closed linear ring. We would expect `0, 0` to be a closed ring.~~ 
Edit: i misunderstood the delta-encoding portion here :) But still the question remains, are the rings closed? Not closing them makes sense from a reduced amount of data transfer

**Comment by JosiahParry** [comment]
Additionally, what winding do Polygons take here? I understand the protobuffer implementation is based on Mapbox's which requires an OGC winding.

**Comment by mmgeorge** [comment]
@JosiahParry the rings should be closed, as in the example above. 

For winding, we use the Esri convention: exterior rings are oriented clockwise, while holes are oriented counterclockwise. Though be careful because server simplification (in general) can change winding order. 

> I understand the protobuffer implementation is based on Mapbox's which requires an OGC winding.

Hmm, I'd say the main similarities with the Mapbox VT encoding spec are that both specs are built on top of Google's ProtocolBuffer spec. In terms of the geometry and value encoding of the features, they are quite different. Whereas the VTL basically specifies a preprocessed tile in isolation, the Esri pbf format doesn't really make sense without considering the parameters you pass the server. 

We did originally experiment with returning attribute values in a way that was more similar to Mapbox, but we found that values like doubles just end up using way more space as for many datasets, features have unique attributes. For reused string data, which I believe is the main reason they took this approach, we instead have the option of using coded domains.

**Comment by JosiahParry** [comment]
Regarding being related to Mapbox: 

https://community.esri.com/t5/arcgis-javascript-maps-sdk-questions/protocolbuffer-binary-format-pbf-documentation-or/m-p/464692/highlight/true#M42964

**Comment by mmgeorge** [comment]
@JosiahParry sorry I was probably confusing there when I was responding to the user, but there are several types of PBF-encoded data that Esri uses. PBF-encoded payloads from FeatureServices (what this repo is) -- in the JSAPI this would be consumed via a `FeatureLayer`. We also support Mapbox's VT spec with Esri's VT basemaps. Those would be confused by the JSAPI as a `VectorTileLayer`.
