### ISSUE TITLE
Feature Service not returning Transform

### ISSUE THREAD

**Issue by JosiahParry** [Esri/arcgis-pbf#16]
As indicated here: https://github.com/Esri/arcgis-pbf/tree/main/proto/FeatureCollection#transform, the transform should always be included. However, that is not the case using this feature service. 

This seems like it may be a bug.

**Comment by JosiahParry** [comment]
repro Feature service: https://services.arcgis.com/cJ9YHowT8TU7DUyn/arcgis/rest/services/FRS_INTERESTS_SEMS_NPL/FeatureServer/0

Note that if I set `out_sr` to 3857 this forces the transform to be present otherwise it is not. This causes problems because the parser used delta encoding as specified by the repo

**Comment by mmgeorge** [comment]
@JosiahParry you did not provide a query

**Comment by JosiahParry** [comment]
Feels a little premature of closure? You can run with a where clause of `1=1` and reproduce it.

**Comment by mmgeorge** [comment]
I'm not sure why you are making all of these posts on this repo when you work at Esri 😅. This is not maintained by the server team & all that we have doc'd is really the narrow use cases used by the JS SDK. The format was originally designed only for quantized tile queries and has since been expanded. For bugs those need to be opened with the relevant product / server team.
