### ISSUE TITLE
Add usage examples to documentation

### ISSUE THREAD

**Issue by steveoh** [Esri/arcgis-pbf#7]
We were debugging an issue with pbf's and were unable to use this repo to figure it all out. For anyone else trying to do the same, https://github.com/rowanwins/arcgis-pbf-parser is a great resource.

Here's a quick code sample of how we used it. We queried a feature service for a pdb, saved it and ran this to view it's contents.

![usage example)](https://user-images.githubusercontent.com/325813/183782740-fb2db624-9f48-4e50-8f9f-0d6fa86e4133.png)

**Comment by mmgeorge** [comment]
@steveoh, the main benefit of PBF is that you can just throw in the spec file into a PBF library and get out a parser. [For the web](https://github.com/Esri/arcgis-pbf/tree/main/proto/FeatureCollection#getting-started), you can have two main options in the form of protoc (the official PBF parser), or protobuf.js.

Once you get out a parser (and you can configure the parser you generate based on your requirements, e.g. typescript, reflection, optimize for build size or speed, etc), then the info [here](https://github.com/Esri/arcgis-pbf/tree/main/proto/FeatureCollection) goes into detail about each of the message types returned and how geometries are encoded.

Trying to figure out where we need to improve the documentation. Is the issue mainly that you are looking for more usage documentation, rather than the spec? I think we might be assuming familiarity with PBF.

**Comment by steveoh** [comment]
Yes some usage examples would be great. We only found examples in the issues. Since the parser is generated by proto libs, it's confusing to have a parser in this repo. We tried to import it and ran into default export issues. But we were able to work past that and kind of decode the pbf but it was still wonky with \u000 binary bits.

**Comment by mmgeorge** [comment]
Thanks @steveoh! We'll look at improving the doc with some more usage examples.

**Comment by mmgeorge** [comment]
Closing this for now, we are removing the generated code & are pointing to protobuf.js which provides some examples on how to work with pbf.
